arch: amd64
os: linux
dist: xenial

env:
  global:
#  - PATH="$HOME/.local/bin:$PATH"
  - FUGUE_VERSION=0.18.0

before_script:
#  - mkdir $HOME/.local/bin
  - curl "https://github.com/fugue/fugue-client/releases/download/v${FUGUE_VERSION}/fugue-linux-amd64" -o fugue
#  - mv fugue-linux-amd64 $HOME/.local/bin/fugue
  - sudo mv fugue /usr/local/bin
  - chmod 755 /usr/local/bin/fugue

script:
  - fugue sync rules my-custom-rules

branches:
  only:
  - main