arch: amd64
os: linux
# dist: trusty

env:
  global:
#  - PATH="$HOME/.local/bin:$PATH"
  - FUGUE_VERSION=0.18.0

script:
#  - mkdir $HOME/.local/bin
  - wget -O fugue https://github.com/fugue/fugue-client/releases/download/v${FUGUE_VERSION}/fugue-linux-amd64
#  - mv fugue-linux-amd64 $HOME/.local/bin/fugue
  - ls -l fugue
  - chmod +x fugue
  - ./fugue --version
  - ls -l fugue
  - sudo mv fugue /usr/local/bin
  - ls -l /usr/local/bin/fugue
  - fugue --version
  - fugue sync rules my-custom-rules

branches:
  only:
  - main